"""
Signals page — current model predictions and rankings.

Displays:
    - Table of predicted 5-day returns, rank, and LONG/FLAT signal.
    - Horizontal bar chart of predicted returns by ticker.

Data is loaded from pre-computed cache files (generated by the notebook).
"""

import streamlit as st
import pandas as pd
import numpy as np
from pathlib import Path

st.set_page_config(page_title="Signals", page_icon="📊", layout="wide")
st.title("📊 Weekly Trading Signals")

# ---------------------------------------------------------------------------
# Load cached predictions
# ---------------------------------------------------------------------------
CACHE_DIR = Path(__file__).resolve().parent.parent / "cache"
PREDICTIONS_PATH = CACHE_DIR / "latest_predictions.parquet"


@st.cache_data(ttl=3600)
def load_predictions() -> pd.DataFrame | None:
    """Load the most recent predictions from cache."""
    if PREDICTIONS_PATH.exists():
        return pd.read_parquet(PREDICTIONS_PATH)
    return None


predictions = load_predictions()

if predictions is None:
    st.warning(
        "No cached predictions found. "
        "Run the notebook (`01_full_pipeline.ipynb`) first to generate predictions, "
        "then copy the output to `app/cache/latest_predictions.parquet`."
    )
    st.stop()

# ---------------------------------------------------------------------------
# Date selector
# ---------------------------------------------------------------------------
available_dates = sorted(predictions["date"].unique(), reverse=True)
selected_date = st.selectbox(
    "Signal date",
    options=available_dates,
    format_func=lambda d: pd.Timestamp(d).strftime("%Y-%m-%d (%A)"),
)

# ---------------------------------------------------------------------------
# Filter and display
# ---------------------------------------------------------------------------
current = predictions[predictions["date"] == selected_date].copy()
current = current.sort_values("predicted_ret", ascending=False).reset_index(drop=True)

# Add rank and signal
current["rank"] = range(1, len(current) + 1)
current["signal"] = np.where(current["predicted_ret"] > 0, "LONG", "FLAT")

# Format for display
display_cols = ["rank", "ticker", "predicted_ret", "signal"]
display_df = current[display_cols].rename(columns={
    "rank": "Rank",
    "ticker": "Ticker",
    "predicted_ret": "Predicted 5d Return (%)",
    "signal": "Signal",
})

col1, col2 = st.columns([1, 1.5])

with col1:
    st.subheader("Signal Table")
    st.dataframe(
        display_df.style.format({"Predicted 5d Return (%)": "{:.2f}"}),
        use_container_width=True,
        hide_index=True,
    )

    n_long = (current["signal"] == "LONG").sum()
    st.metric("Holdings this week", f"{n_long} / {len(current)} stocks")

with col2:
    st.subheader("Predicted Returns")
    try:
        from src.plots import plotly_signal_bars
        fig = plotly_signal_bars(current[["ticker", "predicted_ret"]])
        st.plotly_chart(fig, use_container_width=True)
    except ImportError:
        # Fallback: simple bar chart
        chart_data = current.set_index("ticker")["predicted_ret"].sort_values()
        st.bar_chart(chart_data)

# ---------------------------------------------------------------------------
# Data freshness warning
# ---------------------------------------------------------------------------
latest = pd.Timestamp(available_dates[0])
age_days = (pd.Timestamp.now() - latest).days
if age_days > 7:
    st.warning(
        f"⚠️ Data may be stale — last signal is from {latest.strftime('%Y-%m-%d')} "
        f"({age_days} days ago). Refresh by re-running the data pipeline."
    )
